CREATE TABLE [dbo].[INSCRITOS]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY, 
    [Id_Alumno] INT NOT NULL, 
    [Codigo_Curso] INT NOT NULL, 
    CONSTRAINT [FK_INSCRITOS_ALUMNO] FOREIGN KEY ([Id_Alumno]) REFERENCES [ALUMNO](Id), 
    CONSTRAINT [FK_INSCRITOS_CURSO] FOREIGN KEY ([Codigo_Curso]) REFERENCES [CURSO]([Cod])
)
